// auto generated by go tool dist
// goos=windows goarch=386

#include "runtime.h"
void
runtime·GOMAXPROCS(intgo n, intgo ret)
{
#line 8 "d:\Go1.1\src\pkg\runtime\runtime1.goc"

	ret = runtime·gomaxprocsfunc(n);
	FLUSH(&ret);
}
void
runtime·NumCPU(intgo ret)
{
#line 12 "d:\Go1.1\src\pkg\runtime\runtime1.goc"

	ret = runtime·ncpu;
	FLUSH(&ret);
}
